# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(405, 484)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        MainWindow.setAcceptDrops(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_1.setObjectName("tab_1")
        self.layoutWidget = QtWidgets.QWidget(self.tab_1)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 361, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lw_modes = QtWidgets.QListWidget(self.layoutWidget)
        self.lw_modes.setEnabled(True)
        self.lw_modes.setMaximumSize(QtCore.QSize(110, 16777215))
        self.lw_modes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lw_modes.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lw_modes.setLineWidth(1)
        self.lw_modes.setMidLineWidth(0)
        self.lw_modes.setProperty("isWrapping", False)
        self.lw_modes.setUniformItemSizes(False)
        self.lw_modes.setWordWrap(False)
        self.lw_modes.setObjectName("lw_modes")
        item = QtWidgets.QListWidgetItem()
        self.lw_modes.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw_modes.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw_modes.addItem(item)
        self.horizontalLayout_3.addWidget(self.lw_modes)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sw_mode = QtWidgets.QStackedWidget(self.layoutWidget)
        self.sw_mode.setObjectName("sw_mode")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gain = QtWidgets.QDial(self.page)
        self.gain.setGeometry(QtCore.QRect(20, 120, 81, 81))
        self.gain.setMinimum(1)
        self.gain.setMaximum(255)
        self.gain.setProperty("value", 200)
        self.gain.setTracking(True)
        self.gain.setInvertedAppearance(True)
        self.gain.setInvertedControls(False)
        self.gain.setObjectName("gain")
        self.right = QtWidgets.QProgressBar(self.page)
        self.right.setGeometry(QtCore.QRect(30, 50, 118, 23))
        self.right.setMaximum(255)
        self.right.setProperty("value", 24)
        self.right.setObjectName("right")
        self.general = QtWidgets.QProgressBar(self.page)
        self.general.setGeometry(QtCore.QRect(30, 20, 118, 23))
        self.general.setMaximum(255)
        self.general.setProperty("value", 24)
        self.general.setObjectName("general")
        self.left = QtWidgets.QProgressBar(self.page)
        self.left.setGeometry(QtCore.QRect(30, 80, 118, 23))
        self.left.setMaximum(255)
        self.left.setProperty("value", 24)
        self.left.setObjectName("left")
        self.sw_mode.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.set_color_pb = QtWidgets.QPushButton(self.page_2)
        self.set_color_pb.setGeometry(QtCore.QRect(40, 40, 151, 23))
        self.set_color_pb.setObjectName("set_color_pb")
        self.sw_mode.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.sw_mode.addWidget(self.page_5)
        self.verticalLayout_2.addWidget(self.sw_mode)
        self.setAlMod = QtWidgets.QPushButton(self.layoutWidget)
        self.setAlMod.setObjectName("setAlMod")
        self.verticalLayout_2.addWidget(self.setAlMod)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        self.listWidget.setMaximumSize(QtCore.QSize(130, 16777215))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.groupBox = QtWidgets.QGroupBox(self.page_3)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 211, 111))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.com_ports = QtWidgets.QComboBox(self.groupBox)
        self.com_ports.setObjectName("com_ports")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.com_ports)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.com_speeds = QtWidgets.QComboBox(self.groupBox)
        self.com_speeds.setObjectName("com_speeds")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.com_speeds)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_2.setGeometry(QtCore.QRect(9, -1, 211, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.stackedWidget.addWidget(self.page_4)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pb_connect.setDefault(False)
        self.pb_connect.setObjectName("pb_connect")
        self.horizontalLayout.addWidget(self.pb_connect)
        self.pb_disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.pb_disconnect.setEnabled(False)
        self.pb_disconnect.setCheckable(False)
        self.pb_disconnect.setChecked(False)
        self.pb_disconnect.setAutoRepeat(False)
        self.pb_disconnect.setAutoExclusive(False)
        self.pb_disconnect.setDefault(False)
        self.pb_disconnect.setFlat(False)
        self.pb_disconnect.setObjectName("pb_disconnect")
        self.horizontalLayout.addWidget(self.pb_disconnect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.sw_mode.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.lw_modes.isSortingEnabled()
        self.lw_modes.setSortingEnabled(False)
        item = self.lw_modes.item(0)
        item.setText(_translate("MainWindow", "static color"))
        item = self.lw_modes.item(1)
        item.setText(_translate("MainWindow", "audio lavel"))
        item = self.lw_modes.item(2)
        item.setText(_translate("MainWindow", "fire"))
        self.lw_modes.setSortingEnabled(__sortingEnabled)
        self.set_color_pb.setText(_translate("MainWindow", "set color"))
        self.setAlMod.setText(_translate("MainWindow", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Tab 1"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Srial Port"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Audio in"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "Serial Port Options"))
        self.label.setText(_translate("MainWindow", "Port:"))
        self.label_2.setText(_translate("MainWindow", "Baudrate:"))
        self.pushButton.setText(_translate("MainWindow", "Re-Scan Ports"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Audio in"))
        self.label_3.setText(_translate("MainWindow", "input device"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.pb_connect.setText(_translate("MainWindow", "Connect"))
        self.pb_disconnect.setText(_translate("MainWindow", "Disconnect "))
